name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Thuan3101  # Đảm bảo rằng tên người dùng GitHub là chính xác
          outputs: dist/snake.svg
      - name: Commit and Push
        run: |
          git add dist
          git commit -m "Generated snake"
          git push
