name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Thuan3101  # Đảm bảo rằng tên người dùng GitHub là chính xác
          outputs: dist

      - name: Remove Generated Files
        run: |
          rm -rf dist  # Xóa thư mục dist và các tệp bên trong

      - name: Commit and Push (Optional)
        run: |
          git add -u  # Đảm bảo chỉ thêm các thay đổi đã xóa
          git commit -m "Removed generated snake files"
          git push
